### ISSUE TITLE
Javascript Frontend

### ISSUE THREAD

**Issue by JamesSaxon** [JamesSaxon/access#13]
Adapt mmap to process, post, and display access requests:
- [x] Post single tract "resource" to the AWS lambda function.  To test this, you can just adapt the `map.on('click', function())` in mmap, to send the geoid from the Census back to AWS.  If the lambda function is just returning the times, it should look exactly like the default mmap.
- [x] Add a drop-down or radio button to switch between forms of access.  This can be dummy functionality, until the site is up and running.  N.B. that switching to an already-calculated version of the access should retrieve the cached result from s3 rather than calculating it again.  Since this static http resource will be cached on the client side, switching back and forth should be immediate.
- [x] Figure out how to read in a csv of Census tracts (for now).  Adapt that into a json request to the lambda function.  Somewhere along this line, you'll have to update the server side to read in and "assemble"the matrix from multiple time files, etc.

**Comment by JamesSaxon** [comment]
@jkoschinsky will share (perhaps privately) several additional resources for testing this.

**Comment by jkoschinsky** [comment]
added four destination files on Box (they're non-public):
https://uchicago.app.box.com/folder/81503586477

3 files are for Chicago (groceries, pharmacies and health services)
1 file is for Austria to test the Euclidean distance (social supermarkets)

will upload additional test files soon

**Comment by jkoschinsky** [comment]
as I'm uploading different test data files, I'm realizing we probably need a way to define the spatial extent of the origins. Do we already have that?

E.g. there's a dataset with health resources for Southern IL, which spans several cities and areas inbetween. How do we constrain the tracts that are used as origins for these destinations?

**Comment by JamesSaxon** [comment]
I think that the subtasks laid out in this particular issue are done.  I'm closing, but will make a new, related issue for reproducing access measurements on aws.
