### ISSUE TITLE
Run Docker Access on la2

### ISSUE THREAD

**Issue by JamesSaxon** [JamesSaxon/access#6]
- [x] Document what it takes for this to work, on your own github repo, or in one on GeoDaCenter.
- [x] Make sure Jamie can run it.

**Comment by dfsnow** [comment]
Heads up. I actually got this running fine on la2 using udocker. I'm testing now but everything does seem to be in order. I literally just aliased the udocker executable as docker and it works fine so far.

**Comment by dfsnow** [comment]
Alright, I've tested both routing and resource jobs now and they both work well. Only downside is you can't detach from running containers, so it's a hassle to run multiple jobs at once. I'm running all the resource downloads now. Closing this!
