### ISSUE TITLE
Create a Simplified Geometry of US Tracts from 2010

### ISSUE THREAD

**Issue by JamesSaxon** [JamesSaxon/access#9]
- [x] Download the tract [Cartographic Boundary](https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html) files for all states, for 2010.
- [x] Simplify these using postgres.  See this _old_ [blog post](https://strk.kbt.io/blog/2012/04/13/simplifying-a-map-layer-using-postgis-topology/) or this [gist](https://gist.github.com/JamesSaxon/7bd0f46c35a6b8eca864756419eec30d), which is the same thing.  Do this in CRS 2163.  You are not using the "standard" gdal simplify function, because it simplifies each polygon, instead of each edge.  So each region crumples away from its neighbors, and it looks horrible.
- [x] Export to geojson as 4326, with each county as a separate file.  You should be able to write a script that (a) extracts all distinct counties and then (b) loops over these counties and outputs the geojson.  Check that this works by creating a gist of it.  Link that here.
- [x] Figure out where to put the file containing all these counties.

I have done all this before, for 2015.  So do not flounder.

**Comment by yatlas** [comment]
Here's my [gist](https://gist.github.com/yatlas/ebe459ded7a8e05a2322a1d4aa1b7d00) for exporting counties to a geojson.

**Comment by JamesSaxon** [comment]
Hi Yair --

This will make the county-level, sure -- but these are not the postgis-simplifed versions.  What we want for faster visualization online is the simplified geo -- the export of what you've simplified.  As you do this, please save just the geoid as an int and the geometry itself (i.e., files as small as possible).

See for example here:

https://gis.stackexchange.com/questions/112057/sql-query-to-have-a-complete-geojson-feature-from-postgis/191446#191446

Also, two side notes
- I think your `completedCounties` variable does not get updated, so as you have it, this would make every county file once for each tract in it.  A natural way to avoid this would be to do
`for row in map['COUNTY'].unique()`.
- Avoid `map` as a variable name, since it's a python function.

Thanks -- 

Jamie

**Comment by JamesSaxon** [comment]
Also -- perhaps we should make a branch for this sort of “meta” work on the package??

I hope to be in, in a bit, to chat.

Jamie

**Comment by yatlas** [comment]
Here's a [gist](https://gist.github.com/yatlas/034409cda4c8a53111f06afec2e43674) of simplified Cook County.

**Comment by JamesSaxon** [comment]
Thanks Yair.

GeoJSON geometries look perfect.  Can you take the "1400000US" stuff off of the geoids?  And make it `geoid`, not `geo_id` (we will end up using this variable a bunch, and it will be annoying if it's different).

The scripts in meta just show what's needed to run Illinois.  Can you update simplifier.sql with the loops needed, for the other states?  The scripts should be able to run from scratch -- wget or curl the geometries, then loop over states.

Thanks also, for making the meta branch.  We can, perhaps empty out the "normal" stuff in that branch (do you see any reason to keep it)?
